name: Node.js CI + Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway Deployment
        uses: jwalton/gh-action-railway@v2
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
